from typing import Protocol
from models.product import Product

class ProductRepository(Protocol):
    def list_products(self, is_active: bool) -> list[Product]: ...
    def get_by_id(self, product_id: int) -> Product | None: ...
    def create(self, product: Product) -> Product: ...
    def update(self, product_id: int, product: Product) -> Product: ...
    def delete(self, product_id: int) -> Product: ...
    def search_products(self, name: str = None, presentation: str = None, is_active: bool = True) -> list[Product]: ...