from typing import Protocol
from pathlib import Path


class SFTPClientProtocol(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def list_files(self, remote_path: str) -> list[str]: ...
    def list_files_only(self, remote_path: str) -> list[str]: ...
    def download_file(self, remote_path: str, local_path: Path) -> None: ...
    def upload_file(self, local_path: Path, remote_path: str) -> None: ...
    def delete_file(self, remote_path: str) -> None: ...
    def move_file(self, source: str, target: str) -> None: ...
    def directory_exists(self, remote_path: str) -> bool: ...
    def create_directory(self, remote_path: str) -> None: ...
