from typing import Protocol
from models.product import Product

class ProductService(Protocol):
    def list_products(self, is_active: bool) -> list[Product]: ...
    def get_product(self, product_id: int) -> Product | None: ...
    def create_product(self, product: Product) -> Product: ...
    def update_product(self, product_id: int, product: Product) -> Product: ...
    def delete_product(self, product_id: int) -> Product: ...
    def search_products(self, name: str = None, presentation: str = None, is_active: bool = True) -> list[Product]: ...